# Generated by Django 4.2.4 on 2023-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('course_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
