# Generated by Django 4.2.4 on 2023-08-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=36, null=True)),
                ('teacher_image', models.ImageField(upload_to='teacher')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.details')),
            ],
        ),
    ]
