# Generated by Django 4.2.4 on 2023-08-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='use_name',
            new_name='user_name',
        ),
    ]
